## Data Understanding


# Dataset Column Descriptions: Online Shoppers Purchasing Intention

This dataset contains user session metrics aimed at predicting online shopper purchasing intent (`Revenue`). Below is the detailed documentation for each feature:

| Column Name | Data Type | Description |
| :--- | :--- | :--- |
| **Administrative** | Integer | Number of administrative pages visited by the user during the session. |
| **Administrative_Duration** | Float | Total time spent (in seconds) on administrative pages. |
| **Informational** | Integer | Number of informational pages visited (e.g., About Us, Contact). |
| **Informational_Duration** | Float | Total time spent (in seconds) on informational pages. |
| **ProductRelated** | Integer | Number of product-related pages visited during the session. |
| **ProductRelated_Duration** | Float | Total time spent (in seconds) on product-related pages. |
| **BounceRates** | Float | Percentage of visitors who enter the site and leave after viewing only one page. |
| **ExitRates** | Float | Percentage of pageviews for a specific page that were the last in the session. |
| **PageValues** | Float | Average value of the page measured before a user completes an e-commerce transaction. |
| **SpecialDay** | Float | Closeness of the visit time to a specific holiday or special event (scaled from 0 to 1). |
| **Month** | Categorical | Month in which the user session took place. |
| **OperatingSystems** | Integer | Anonymized identifier for the user's operating system. |
| **Browser** | Integer | Anonymized identifier for the web browser used. |
| **Region** | Integer | Anonymized geographic region code of the user. |
| **TrafficType** | Integer | Anonymized code representing the source/traffic channel (e.g., Direct, Ads, Organic). |
| **VisitorType** | Categorical | Categorization of the user (`Returning_Visitor`, `New_Visitor`, `Other`). |
| **Weekend** | Boolean | Indicates whether the session occurred on a weekend (`True`/`False`). |
| **Revenue** | Boolean | **Target Class**: Indicates whether the session resulted in a purchase (`True`/`False`). |

In [64]:
import numpy as np
import pandas as pd 
import plotly.express as px

In [65]:
df=pd.read_csv('online_shoppers_intention.csv')
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False


## Data Exploration

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Administrative           12330 non-null  int64  
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64  
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64  
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object 
 11  OperatingSystems         12330 non-null  int64  
 12  Browser                  12330 non-null  int64  
 13  Region                   12330 non-null  int64  
 14  TrafficType           

In [67]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000


In [68]:
df.isna().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(125)

In [70]:
df.drop_duplicates(inplace=True)

In [71]:
df['Revenue'] = df['Revenue'].astype(int)
df['Weekend'] = df['Weekend'].astype(int)

## Data Cleaning


In [72]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,0,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,0,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,0,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,0,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,1,0


In [73]:
num_col=df.select_dtypes(include=['number']).columns

In [74]:
cat_cols = ['OperatingSystems', 'Browser', 'Region', 'TrafficType']
for col in cat_cols:
    df[col] = df[col].astype('object')

In [75]:
for col in num_col:
    px.histogram(df, x=col,title=f'Histogram of {col}').show()
    px.box(df, y=col, title=f'Boxplot of {col} ').show()

In [76]:
cat=df.select_dtypes(include=['object']).columns

In [77]:
for col in cat :
    print(col)
    print(df[col].unique())
    print(df[col].nunique())
    print('*'*100)

Month
['Feb' 'Mar' 'May' 'Oct' 'June' 'Jul' 'Aug' 'Nov' 'Sep' 'Dec']
10
****************************************************************************************************
OperatingSystems
[1 2 4 3 7 6 8 5]
8
****************************************************************************************************
Browser
[1 2 3 4 5 6 7 10 8 9 12 13 11]
13
****************************************************************************************************
Region
[1 9 2 3 4 5 6 7 8]
9
****************************************************************************************************
TrafficType
[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 18 19 16 17 20]
20
****************************************************************************************************
VisitorType
['Returning_Visitor' 'New_Visitor' 'Other']
3
****************************************************************************************************


In [78]:
df['Month'].unique()

array(['Feb', 'Mar', 'May', 'Oct', 'June', 'Jul', 'Aug', 'Nov', 'Sep',
       'Dec'], dtype=object)

In [79]:
df['Month'] = df['Month'].replace({'June': 'Jun'})

In [80]:
## delete outliers such as ProductRelated_Duration > 43200 seconds (12 hours)
df=df[df['ProductRelated_Duration'] <= 43200]

In [81]:
df =df[~((df['BounceRates'] == 0.2) & (df['Revenue'] == 1))]

## Data Analysis

- Question 1: What is the overall Conversion Rate and target class distribution?

In [82]:
total_sessions = len(df)
purchases = df['Revenue'].sum()
no_purchases = total_sessions - purchases
conversion_rate = df['Revenue'].mean() * 100

print(f"Total Sessions: {total_sessions}")
print(f"Purchases (Revenue = 1): {purchases} ({conversion_rate:.2f}%)")
print(f"No Purchases (Revenue = 0): {no_purchases} ({100 - conversion_rate:.2f}%)\n")

Total Sessions: 12201
Purchases (Revenue = 1): 1905 (15.61%)
No Purchases (Revenue = 0): 10296 (84.39%)



In [83]:
fig = px.pie(df, 
             names='Revenue', 
             title='Revenue Distribution (Conversion Rate)',
             labels={0: 'No Purchase', 1: 'Purchase'},
             color='Revenue')
fig.show()

-Business Insight: يوضح هذا أن المتجر يفقد ما يقرب من 84% من إجمالي الحركة (Traffic) الوافدة إليه، مما يستدعي دراسة سلوك الزوار في باقي الأسئلة لكشف أسباب المغادرة وتصميم استراتيجيات لتحسين نسبة الشراء.  

- Question 2: Does the Visitor Type affect the Conversion Rate?

In [84]:
vist_df=df.groupby('VisitorType')['Revenue'].value_counts(normalize=True).reset_index(name='Percentage').sort_values(by='Percentage', ascending=False)
vist_df['Percentage'] = vist_df['Percentage'] * 100
vist_df

,VisitorType,Revenue,Percentage
4,Returning_Visitor,0,85.930757
2,Other,0,80.246914
0,New_Visitor,0,75.073833
1,New_Visitor,1,24.926167
3,Other,1,19.753086
5,Returning_Visitor,1,14.069243


In [85]:
px.bar(vist_df, x='VisitorType', y='Percentage', color='Revenue', barmode='group', title='Revenue Distribution by Visitor Type').show()

- New Visitor Intent: تسجل شريحة الزوار الجدد (New_Visitor) نسبة تحويل عالية قدرها 24.93% (تقريباً زائر من كل 4 زوار يشتري).  
Returning Visitor Drop: تسجل شريحة الزوار القدامى المكررين (Returning_Visitor) معدل تحويل أقل يبلغ 14.07%. 
Takeaway: حملات جلب العملاء الجدد تبلي بلاءً حسناً، بينما الزوار القدامى يحتاجون استراتيجيات تحفيزية إضافية لمنع مغادرتهم المتجر دون شراء.

- Question 3: How strongly does Page Values impact the purchase decision?

In [86]:
df['PageValues'].describe()

count    12201.000000
mean         5.951524
std         18.656418
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        361.763742
Name: PageValues, dtype: float64

In [87]:
df['page_value_category'] = pd.cut(df['PageValues'],
                                   bins=[-1, 0, 10, 50, 400], 
                                   labels=['Zero (0)', 'Low (1-10)', 'Medium (10-50)', 'High (>50)'])

In [88]:
df_page=df.groupby('page_value_category')['Revenue'].value_counts(normalize=True).reset_index(name='Percentage').sort_values(by='Percentage', ascending=False)
df_page['Percentage'] = df_page['Percentage'] * 100
df_page


C:\Users\ALSAAD\AppData\Local\Temp\ipykernel_24408\718525347.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_page=df.groupby('page_value_category')['Revenue'].value_counts(normalize=True).reset_index(name='Percentage').sort_values(by='Percentage', ascending=False)


,page_value_category,Revenue,Percentage
0,Zero (0),0,96.125013
6,High (>50),1,81.127451
2,Low (1-10),0,61.637931
4,Medium (10-50),1,61.047346
5,Medium (10-50),0,38.952654
3,Low (1-10),1,38.362069
7,High (>50),0,18.872549
1,Zero (0),1,3.874987


In [89]:
px.bar(df_page, x='page_value_category', y='Percentage', color='Revenue', barmode='group', title='Revenue Distribution by Page Value Category',text_auto=True).show()

- Question 4: Does spending more time on product-related pages increase the Conversion Rate?

In [90]:
df['product_minutes'] = df['ProductRelated_Duration'] / 60
df['product_category'] = pd.cut(df['product_minutes'],
                                bins=[-1, 5, 20, 60, 2000],
                                labels=['Very Low (<5m)', 'Low (5-20m)', 'Medium (20-60m)', 'High (>60m)'])
                                

In [91]:
df_min=df.groupby('product_category')['Revenue'].value_counts(normalize=True).reset_index(name='Percentage').sort_values(by='Percentage', ascending=False)
df_min['Percentage'] = df_min['Percentage'] * 100

C:\Users\ALSAAD\AppData\Local\Temp\ipykernel_24408\1079176873.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_min=df.groupby('product_category')['Revenue'].value_counts(normalize=True).reset_index(name='Percentage').sort_values(by='Percentage', ascending=False)


In [92]:
px.bar(df_min, x='product_category', y='Percentage', color='Revenue', barmode='group', title='Revenue Distribution by Product Related Duration Category',text_auto=True).show()

- Question 5: Which Traffic Channels have the highest and lowest Conversion Rates?

In [93]:
top_channels = df['TrafficType'].value_counts().head(6).index
df['Traffic_Grouped'] = df['TrafficType'].apply(lambda x: str(x) if x in top_channels else 'Other')
traffic_df=df.groupby('Traffic_Grouped')['Revenue'].value_counts(normalize=True).reset_index(name='Percentage')
traffic_df['Percentage'] = (traffic_df['Percentage'] * 100).round(2)
traffic_df

,Traffic_Grouped,Revenue,Percentage
0,1,0,89.03
1,1,1,10.97
2,10,0,80.00
3,10,1,20.00
4,13,0,94.09
5,13,1,5.91
6,2,0,78.34
7,2,1,21.66
8,3,0,91.06
9,3,1,8.94


In [94]:
px.bar(
    traffic_df, 
    x='Traffic_Grouped', 
    y='Percentage', 
    color='Revenue', 
    barmode='group',
    text_auto='.2f',
    title='Conversion Rate (%) across Different Traffic Types',
    labels={'TrafficType': 'Traffic Type (Channel)', 'Percentage': 'Percentage (%)', 'Revenue_Status': 'Revenue Status'},
    color_discrete_map={'No Purchase (0)': '#EF553B', 'Purchase (1)': '#00CC96'} # أحمر لعدم الشراء وأخضر للشراء
).show()

In [95]:
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,Browser,Region,TrafficType,VisitorType,Weekend,Revenue,page_value_category,product_minutes,product_category,Traffic_Grouped
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,...,1,1,1,Returning_Visitor,0,0,Zero (0),0.000000,Very Low (<5m),1
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,...,2,1,2,Returning_Visitor,0,0,Zero (0),1.066667,Very Low (<5m),2
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,...,1,9,3,Returning_Visitor,0,0,Zero (0),0.000000,Very Low (<5m),3
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,...,2,2,4,Returning_Visitor,0,0,Zero (0),0.044444,Very Low (<5m),4
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,...,3,1,4,Returning_Visitor,1,0,Zero (0),10.458333,Low (5-20m),4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,...,6,1,1,Returning_Visitor,1,0,Medium (10-50),29.729861,Medium (20-60m),1
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,...,2,1,8,Returning_Visitor,1,0,Zero (0),7.762500,Low (5-20m),Other
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,...,2,1,13,Returning_Visitor,1,0,Zero (0),3.070833,Very Low (<5m),13
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,...,2,3,11,Returning_Visitor,0,0,Zero (0),5.766667,Low (5-20m),Other


- Question 6: How do Bounce Rates and Exit Rates correlate with Page Values and Purchase Intent?

In [96]:
px.scatter(df,x='BounceRates',y='ExitRates',color='Revenue',size='PageValues',title='Bounce Rates vs Exit Rates with Page Values and Revenue Status').show()

- ده معنها اني كل لم تقل نسبه عن 0.05 ل exit rate, bounce rate , page value بتعبر بحجم الدائره فا ده بيزود من نسبه الشراء

## Machine Learning 

In [97]:
df

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,Browser,Region,TrafficType,VisitorType,Weekend,Revenue,page_value_category,product_minutes,product_category,Traffic_Grouped
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,...,1,1,1,Returning_Visitor,0,0,Zero (0),0.000000,Very Low (<5m),1
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,...,2,1,2,Returning_Visitor,0,0,Zero (0),1.066667,Very Low (<5m),2
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,...,1,9,3,Returning_Visitor,0,0,Zero (0),0.000000,Very Low (<5m),3
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,...,2,2,4,Returning_Visitor,0,0,Zero (0),0.044444,Very Low (<5m),4
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,...,3,1,4,Returning_Visitor,1,0,Zero (0),10.458333,Low (5-20m),4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,...,6,1,1,Returning_Visitor,1,0,Medium (10-50),29.729861,Medium (20-60m),1
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,...,2,1,8,Returning_Visitor,1,0,Zero (0),7.762500,Low (5-20m),Other
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,...,2,1,13,Returning_Visitor,1,0,Zero (0),3.070833,Very Low (<5m),13
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,...,2,3,11,Returning_Visitor,0,0,Zero (0),5.766667,Low (5-20m),Other


In [98]:
x=df.drop('Revenue', axis=1)
y=df['Revenue']

In [99]:
num_col=x.select_dtypes(include=['number']).columns
obj_col=x.select_dtypes(include=['object']).columns
obj_col

Index(['Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType',
       'VisitorType', 'Traffic_Grouped'],
      dtype='object')

In [100]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
rc=RobustScaler()
num_pipeline=Pipeline(steps=[('scaler', rc)])


In [101]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(handle_unknown='ignore', sparse_output=False)
cat_pipeline=Pipeline(steps=[('onehot', ohe)])

- Assign each column to its corresponding Pipeline

In [102]:
from sklearn.compose import ColumnTransformer

preprocessing = ColumnTransformer(transformers= [ ('Num Pipeline', num_pipeline, num_col),
                                                  ('categorical Pipeline', cat_pipeline, obj_col) ])
preprocessing

,transformers,"[('Num Pipeline', ...), ('categorical Pipeline', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True
,force_int_remainder_cols,'deprecated'
,with_centering,True
,with_scaling,True
,quantile_range,"(25.0, ...)"


### Selecting Best Model

In [103]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 42, stratify= y)

In [104]:
y_train.value_counts(normalize= True)*100

Revenue
0    84.385246
1    15.614754
Name: proportion, dtype: float64

In [105]:
major_class = y_train.value_counts()[0]
major_class

np.int64(8236)

In [106]:
minor_class=y_train.value_counts()[1]
minor_class

np.int64(1524)

In [107]:
scale_pos_weight = major_class / minor_class

In [108]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import cross_validate

models = [
    ('Logistic Regression', LogisticRegression(random_state= 42, class_weight= 'balanced')),
    # ('KNN', KNeighborsClassifier()),
    ('Gaussian NB', GaussianNB()),
    # ('SVC', SVC(random_state= 42)),
    ('Decision Tree', DecisionTreeClassifier(random_state= 42, class_weight = 'balanced')),
    ('Random Forest', RandomForestClassifier(random_state= 42, class_weight = 'balanced')),
    ('XGBoost', XGBClassifier(random_state= 42, scale_pos_weight = scale_pos_weight))
]

for model in models:
    
    model_pipeline = Pipeline(steps= [('Preprocessing',preprocessing),
                                      ('Model', model[1])])
    
    cv_result = cross_validate(estimator= model_pipeline,
                                X= x_train,
                                y= y_train,
                                scoring= ['precision', 'recall'],
                                cv= 5,
                                return_train_score= True,
                                n_jobs= -1
                                )
    
    print(model[0])
    print('Train Precision :', cv_result['train_precision'].mean().round(4) * 100)
    print('Test Precision :', cv_result['test_precision'].mean().round(4) * 100)

    print('Train Recall :', cv_result['train_recall'].mean().round(4) * 100)
    print('Test Recall :', cv_result['test_recall'].mean().round(4) * 100)
    print('\n')

Logistic Regression
Train Precision : 51.9
Test Precision : 50.82
Train Recall : 77.59
Test Recall : 76.51


Gaussian NB
Train Precision : 22.15
Test Precision : 21.94
Train Recall : 91.08000000000001
Test Recall : 90.62


Decision Tree
Train Precision : 100.0
Test Precision : 56.88999999999999
Train Recall : 100.0
Test Recall : 55.19


Random Forest
Train Precision : 100.0
Test Precision : 75.98
Train Recall : 99.97
Test Recall : 50.59


XGBoost
Train Precision : 91.9
Test Precision : 62.79
Train Recall : 99.97
Test Recall : 70.39999999999999




## Hyberparameter tuning

In [109]:
rf_pipeline =  Pipeline(
    steps=[
        ('Preprocessing', preprocessing),
        ('Model', XGBClassifier(
            random_state=42,
            scale_pos_weight=scale_pos_weight
        ))
    ]
)

In [110]:
param_grid = {'Model__max_depth' : [5, 6, 7],
              'Model__n_estimators' : [50, 100, 200]}
param_grid

{'Model__max_depth': [5, 6, 7], 'Model__n_estimators': [50, 100, 200]}

In [111]:
from sklearn.model_selection import RandomizedSearchCV

randomized_search = RandomizedSearchCV(rf_pipeline, param_grid, n_iter= 6, cv= 5, scoring= 'recall', return_train_score= True, n_jobs= -1)

In [112]:
randomized_search.fit(x_train, y_train)

,estimator,"Pipeline(step...=None, ...))])"
,param_distributions,"{'Model__max_depth': [5, 6, ...], 'Model__n_estimators': [50, 100, ...]}"
,n_iter,6
,scoring,'recall'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [113]:
randomized_search.cv_results_['mean_train_score']

array([1.        , 0.99803185, 0.98622023, 1.        , 0.96177813,
       0.99393039])

In [114]:
randomized_search.cv_results_['mean_test_score']

array([0.65744823, 0.72570966, 0.76441544, 0.68828947, 0.78474978,
       0.74014236])

In [115]:
randomized_search.best_score_

np.float64(0.7847497842968075)

In [116]:
randomized_search.best_params_

{'Model__n_estimators': 50, 'Model__max_depth': 5}

In [117]:
import joblib
joblib.dump(randomized_search, 'best_model.pkl')

['best_model.pkl']

In [118]:
rf_model = joblib.load('best_model.pkl')
rf_model

,estimator,"Pipeline(step...=None, ...))])"
,param_distributions,"{'Model__max_depth': [5, 6, ...], 'Model__n_estimators': [50, 100, ...]}"
,n_iter,6
,scoring,'recall'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [119]:
rf_model.predict(x.head(1))[0]

np.int64(0)

In [120]:
x.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,page_value_category,product_minutes,product_category,Traffic_Grouped
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,1,1,1,1,Returning_Visitor,0,Zero (0),0.000000,Very Low (<5m),1
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,2,2,1,2,Returning_Visitor,0,Zero (0),1.066667,Very Low (<5m),2
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,4,1,9,3,Returning_Visitor,0,Zero (0),0.000000,Very Low (<5m),3
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,3,2,2,4,Returning_Visitor,0,Zero (0),0.044444,Very Low (<5m),4
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,3,3,1,4,Returning_Visitor,1,Zero (0),10.458333,Low (5-20m),4


In [125]:
!pip install pipreqs
import pipreqs
! pipreqs . /

  Using cached pipreqs-0.5.0-py3-none-any.whl.metadata (7.9 kB)
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached ipython-8.12.3-py3-none-any.whl.metadata (5.7 kB)
  Using cached yarg-0.1.9-py2.py3-none-any.whl.metadata (4.6 kB)
  Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB)
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl.metadata (1.5 kB)
Using cached pipreqs-0.5.0-py3-none-any.whl (33 kB)
Using cached ipython-8.12.3-py3-none-any.whl (798 kB)
Using cached yarg-0.1.9-py2.py3-none-any.whl (19 kB)
Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
  Created wheel

Usage:
    pipreqs [options] [<path>]


In [126]:
import pipreqs

!pipreqs .

INFO: Not scanning for jupyter notebooks.
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in .\requirements.txt


In [127]:
print(pd.__version__)

2.2.3
